package com.apkinves.toolbox.features.password

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.Checkbox
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Slider
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.apkinves.toolbox.core.net.PwnedPasswordClient
import com.apkinves.toolbox.core.util.PasswordUtils
import com.apkinves.toolbox.ui.common.ResultBlock
import kotlinx.coroutines.launch

@Composable
fun PasswordScreen() {
    var length by remember { mutableStateOf(16f) }
    var useUpper by remember { mutableStateOf(true) }
    var useDigits by remember { mutableStateOf(true) }
    var useSymbols by remember { mutableStateOf(true) }
    var generated by remember { mutableStateOf("") }

    var checkInput by remember { mutableStateOf("") }
    var checkResult by remember { mutableStateOf("") }
    var pwnedResult by remember { mutableStateOf("") }
    var pwnedLoading by remember { mutableStateOf(false) }
    val scope = rememberCoroutineScope()

    Column(
        modifier = Modifier.fillMaxWidth().padding(16.dp).verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(12.dp),
    ) {
        Text("Generador de contraseñas", style = MaterialTheme.typography.headlineSmall)
        Text("Longitud: ${length.toInt()}")
        Slider(value = length, onValueChange = { length = it }, valueRange = 6f..64f)

        Row {
            Checkbox(checked = useUpper, onCheckedChange = { useUpper = it }); Text("Mayúsculas", Modifier.padding(top = 12.dp))
        }
        Row {
            Checkbox(checked = useDigits, onCheckedChange = { useDigits = it }); Text("Dígitos", Modifier.padding(top = 12.dp))
        }
        Row {
            Checkbox(checked = useSymbols, onCheckedChange = { useSymbols = it }); Text("Símbolos", Modifier.padding(top = 12.dp))
        }

        Button(
            onClick = { generated = PasswordUtils.generate(length.toInt(), useUpper, useDigits, useSymbols) },
            modifier = Modifier.fillMaxWidth(),
        ) { Text("Generar") }
        ResultBlock(generated)

        Text("Medidor de fortaleza", style = MaterialTheme.typography.headlineSmall)
        OutlinedTextField(
            value = checkInput,
            onValueChange = {
                checkInput = it
                pwnedResult = ""
                val s = PasswordUtils.estimateStrength(it)
                checkResult = "Fortaleza: ${s.label}\nEntropía estimada: ${"%.1f".format(s.bits)} bits\n" +
                    "Tiempo estimado de crackeo (ataque offline rápido): ${s.crackTimeLabel}"
            },
            label = { Text("Contraseña a evaluar") },
            modifier = Modifier.fillMaxWidth(),
            singleLine = true,
        )
        ResultBlock(checkResult)

        Text(
            "Solo se envían los 5 primeros caracteres del hash SHA-1 " +
                "(k-anonimato de Have I Been Pwned) — la contraseña nunca sale " +
                "completa ni en texto plano ni como hash completo.",
            style = MaterialTheme.typography.bodySmall,
        )
        Button(
            onClick = {
                pwnedLoading = true
                scope.launch {
                    val result = PwnedPasswordClient.check(checkInput)
                    pwnedResult = result.fold(
                        onSuccess = {
                            if (it.timesSeen > 0) "⚠ Esta contraseña ha aparecido en filtraciones conocidas ${it.timesSeen} veces. No la uses."
                            else "✓ No aparece en las filtraciones conocidas por Have I Been Pwned."
                        },
                        onFailure = { "Error: ${it.message}" },
                    )
                    pwnedLoading = false
                }
            },
            enabled = checkInput.isNotBlank() && !pwnedLoading,
            modifier = Modifier.fillMaxWidth(),
        ) { Text(if (pwnedLoading) "Comprobando..." else "¿Se ha filtrado esta contraseña?") }
        ResultBlock(pwnedResult)
    }
}
